SaltStackWebApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='saltweb')),
    path('admin/', admin.site.urls),
    path('saltweb/', include("saltweb.urls")),
]

saltweb/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'saltweb'
urlpatterns = [
    path('', RedirectView.as_view(url="index")),
    path('index', views.IndexView.as_view(), name='index'),
    path('thanks', views.Thanks.as_view()),
    path('experiences', views.ExperiencesList.as_view()),
]

saltweb/models.py
from django.db import models


class UserExperienceModel(models.Model):
    name = models.CharField(max_length=255)
    experience = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.name

saltweb/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import UserExperienceModel


class UserExperienceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserExperienceForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nombre:'
        self.fields['experience'].label = 'Qué tul?'
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'index'

        self.helper.add_input(
            Submit('submit', 'Submit', css_class="float-right")
        )

    class Meta:
        model = UserExperienceModel
        fields = [
            'name',
            'experience',
        ]

saltweb/views.py
import os
from datetime import datetime

from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.apps import apps
from django.shortcuts import redirect

from .forms import UserExperienceForm
from .models import UserExperienceModel


class IndexView(CreateView):
    template_name = 'saltweb/index.html'
    success_url = '/saltweb/thanks'
    form_class = UserExperienceForm

    def get_context_data(self, **kwargs):
        app = apps.get_app_config('saltweb')
        hostname = os.uname().nodename
        visits_count = 0
        hostname_visits_count = 0
        if app.redis:
            visits_count = app.redis.hget("global", "visits").decode()
            hostname_visits_count = app.redis.hget(hostname, "visits").decode()

            if not app.redis.hgetall(hostname):
                app.redis.hmset(hostname, {
                    "visits": 0,
                })

            app.redis.hincrby("global", "visits", 1)
            app.redis.hincrby(hostname, "visits", 1)

        context = super().get_context_data(**kwargs)
        context.update({
            'hostname': hostname,
            'visits_count': visits_count,
            'hostname_visits_count': hostname_visits_count,
        })
        return context

    def post(self, request, **kwargs):
        form = self.get_form()
        exp = form.save(commit=False)
        exp.date = datetime.now()
        exp.save()
        return redirect(self.success_url)


class Thanks(TemplateView):
    template_name = 'saltweb/thanks.html'


class ExperiencesList(ListView):
    template_name = 'saltweb/experiences.html'
    model = UserExperienceModel

saltweb/templates/saltweb/base.html
{% load static %}
<!DOCTYPE html>
<html class="h-100">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}Salt Web App{% endblock title %}</title>
        {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="{% static 'saltweb/css/base.css' %}" type="text/css">
        {% endblock css %}
        {% block js %}
        <script
          src="https://code.jquery.com/jquery-3.4.1.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
          crossorigin="anonymous"></script>
        <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
          crossorigin="anonymous"></script>
        {% endblock js %}
        {% endblock head %}
    </head>
    <body class="d-flex flex-column h-100">
        {% block body %}
        <header>
        {% block navbar %}
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
          <a class="navbar-brand" href="/">SaltStack WebApp</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            {% block menu %}
              <li class="nav-item active">
                <a class="nav-link" href="/">Casucha<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="experiences">Experiencias<span class="sr-only">(current)</span></a>
              </li>
            {% endblock menu %}
            </ul>
          </div>
        </nav>
        {% endblock navbar %}
        </header>
        {% block main %}
        <main class="flex-shrink-0">
            <div class="container">
                {% block maincontainer %}
                {% endblock maincontainer %}
            </div>
        </main>
        {% endblock main %}
        {% block footer %}
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span>SaltStack Prove of Concept by Sebastián Kennedy &amp; Martín Cuesta</span>
            </div>
        </footer>
        {% endblock footer %}
        {% endblock body %}
    </body>
</html>

saltweb/templates/saltweb/experiences.html
{% extends "saltweb/base.html" %}

{% block maincontainer %}
<div class="thanks-container">
    <h1 class="text-center">
        Lo que dice la people...
    </h1>
    <div class="table-responsive-sm">
    <table class="table table-light table-striped table-hover">
        <thead class="thead-dark">
            <th>Nombre</th>
            <th>Comentario</th>
        </thead>
        <tbody>
            {% for exp in object_list %}
            <tr>
                <td>{{ exp.name }}</td>
                <td>{{ exp.experience }}</td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock maincontainer %}

saltweb/templates/saltweb/index.html
{% extends "saltweb/base.html" %}
{% load static crispy_forms_tags %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'saltweb/css/index.css' %}" type="text/css">
{% endblock css %}

{% block maincontainer %}
<div class="index-container">
    <h1 class="text-center">
        Aloha Terrícolas!
    </h1>
    <p>
        Bienvenidos a la Prueba de Concepto de SaltStack.
    </p>
    <p>
        Si esperaban encontrar una App útil, buscaron en el lugar equivocado.
    </p>
    <p>
    Esta solicitud fue recibida por la siguiente máquina: <span class="hostname-label">{{ hostname }}</span>.
    </p>
    <p>
    La página ha recibido <b>{{ visits_count }}</b> visitas desde que alguien la puso a correr. Esta máquina en particular recibió <b>{{ hostname_visits_count }}</b> visitas.
    </p>
    <div class="formContainer jumbotron">
        <h3><b>Qué te pareció la página?</b></h3>
        {% crispy form form.helper %}
    </div>
</div>
{% endblock maincontainer %}

saltweb/templates/saltweb/thanks.html
{% extends "saltweb/base.html" %}

{% block maincontainer %}
<div class="thanks-container col-12">
    <div class="col-12">
        <h1 class="text-center">
            Gracias campeón! <i class="fa fa-hand-rock-o" aria-hidden="true"></i>
        </h1>
    </div>
    <div class="col-12">
        <a class="btn btn-primary " href="{% url 'saltweb:index' %}">Volver a casa</a>
    </div>
</div>
{% endblock maincontainer %}